baseURL = "/"
languageCode = "en-us"
title = "FAIRPoints"
themesDir = "themes"
theme = "hugo-serif-theme"

[module]
  [module.hugoVersion]
    extended = true
    min = "0.55.0"

[params]
  # In most cases you will only want to use either one of these. If you have Google Analytics included in your GTM tags don't put your GA ID here. Otherwise your data might be useless.
  google_analytics_id = ""
  google_tag_manager_id = ""

  [params.homepage]
    show_contact_box = true # show / hide the contaxt box on the homepage
    show_services_button = true  # show / hide the "view all services" button

  [params.logo]
    mobile = "images/logo/FAIRPoints.logo.svg"
    mobile_height = "36px"
    desktop = "images/logo/FAIRPoints.logo.svg"
    desktop_height = "160px"
    alt = "FAIRPoints"

  [params.seo]
    meta_twitter_site = "@FAIR_Points"
    meta_twitter_creator = "@FAIR_Points"

  [params.team]
    summary_large_truncate = 120  # How many characters to include in the summary of the team bios (large layout) before truncating

  [params.footer]
    copyright_text = 'Website built with <a href="https://hugo.io">Hugo</a> using the <a href="https://www.zerostatic.io">Hugo Serif theme</a>.'

[menu]
  # Main Menu
  [[menu.main]]
      name = "Home"
      url = "/"
      weight = 1
  [[menu.main]]
          name = "Events"
          url = "/events/"
          weight = 2
  [[menu.main]]
    name = "Get involved"
    url = "/involved/"
    weight = 3
  [[menu.main]]
        name = "Team"
        url = "/team/"
        weight = 4
  [[menu.main]]
      name = "Contact"
      url = "/contact/"
      weight = 5


  # Footer Menu
  [[menu.footer]]
    name = "Home"
    url = "/"
      weight = 1

  [[menu.footer]]
    name = "Contact"
    url = "/contact/"
      weight = 2
